version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: deploy/before.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/start.sh
      timeout: 300
      runas: root
permissions:
  - object: /home/ec2-user/deploy
    mode: 644
    acls:
      - "d:u::rwx"
      - "d:g::rwx"
      - "d:o::rwx"
    owner: ec2-user
    type:
      - directory