version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user
hooks:
  BeforeInstall:
    - location: deploy/before.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/start.sh
      timeout: 300
      runas: root
permissions:
  - object: /home/ec2-user/deploy
    pattern: "**"
    mode: 777
    type:
      - file 